@startuml
actor "Ciudadano" as C
boundary "IU Pantalla" as IU
control "Sistema" as Sys
entity "Bache" as B
entity "InformeRotura" as IR
boundary "IU Impresor" as IUI

C -> IU: Ingresa datos y ubicación
IU -> Sys: buscarCiudadano(datos)
Sys --> IU: ok
IU -> Sys: registrarBache(ubicación, etc)
Sys -> B: new Bache(...)
Sys -> IR: new InformeRotura(bache, ciudadano, ...)
Sys -> IUI: imprimirConstancia()
Sys --> IU: fechaEstimadaReparacion
IU --> C: Muestra datos y fecha estimada
@enduml